name: Build and Push Laravel Image on Tag or Release

on:
  push:
    tags:
      - '*'  # Esto se ejecuta con cualquier tag, puedes usar v* para tags específicos como v1.0.0
  release:
    types: [created]  # Solo cuando se crea una nueva release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          REPO_NAME="${{ github.repository_owner }}"
          REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')  # Convierte el nombre del repositorio a minúsculas
          docker build -t ghcr.io/$REPO_NAME/laravel-app:${{ github.ref_name }} .

      - name: Push Docker image to GitHub Packages
        run: |
          REPO_NAME="${{ github.repository_owner }}"
          REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')  # Convierte el nombre del repositorio a minúsculas
          docker push ghcr.io/$REPO_NAME/laravel-app:${{ github.ref_name }}
