name: Build and Push Laravel Image on Tag or Release

on:
  push:
    tags:
      - '*'  # Ejecuta cuando se empuja un tag
  release:
    types: [created]  # Solo al crear una release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')/laravel-app:$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]') .

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')/laravel-app:$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
